/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-09-19 05:48:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Car Database</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <center>\r\n");
      out.write("        <h1>Car Rental Suite</h1>\r\n");
      out.write("        \r\n");
      out.write("    </center>\r\n");
      out.write("<div align=\"center\">>\r\n");
      out.write("       \r\n");
      out.write("            <form action=\"insertUser\" method=\"post\">\r\n");
      out.write("        \r\n");
      out.write("        <table border=\"1\" cellpadding=\"5\">\r\n");
      out.write("            <caption>\r\n");
      out.write("                <h2>\r\n");
      out.write("                    \r\n");
      out.write("                        Add New user\r\n");
      out.write("                    \r\n");
      out.write("                </h2>\r\n");
      out.write("            </caption>\r\n");
      out.write("                      \r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Phone number: </th>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"text\" name=\"phone_no\" size=\"20\"                          \r\n");
      out.write("                       pattern=\"[0-9]{10}\" title=\"Ten digit phone number\"\r\n");
      out.write("                   required placeholder=\"9856231478\" autofocus />\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <th>First Name: </th>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"text\" name=\"first_name\" size=\"20\"\r\n");
      out.write("                             required\r\n");
      out.write("                    />\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Last Name: </th>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"text\" name=\"last_name\" size=\"45\"\r\n");
      out.write("                             required\r\n");
      out.write("                    />\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("           <tr>\r\n");
      out.write("                <th>Address: </th>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"text\" name=\"address\" size=\"150\"\r\n");
      out.write("                             required\r\n");
      out.write("                    />\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Email: </th>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"text\" name=\"email_id\" size=\"45\"\r\n");
      out.write("                             required placeholder=\"aswin.r@wipro.com\"\r\n");
      out.write("                    />\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("            <th>User Name: </th>\r\n");
      out.write("            <td>\r\n");
      out.write("            <input type=\"text\" name=\"user_name\" size=\"45\"\r\n");
      out.write("                             required/>\r\n");
      out.write("            </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("            <th>Password:</th>\r\n");
      out.write("            <td>\r\n");
      out.write("            <input type=\"password\" name=\"password\" size=\"45\"\r\n");
      out.write("                             required id=\"password\"\r\n");
      out.write("                    />\r\n");
      out.write("               </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               \r\n");
      out.write("           <tr>\r\n");
      out.write("           <th>Confirm password:</th>\r\n");
      out.write("           <td>\r\n");
      out.write("           <input name=\"password_confirm\" required type=\"password\" id=\"password_confirm\" oninput=\"check(this)\" size=\"45\" />\r\n");
      out.write("           <script language='javascript' type='text/javascript'>\r\n");
      out.write("       function check(input) {\r\n");
      out.write("        if (input.value != document.getElementById('password').value) {\r\n");
      out.write("            input.setCustomValidity('Password Must be Matching.');\r\n");
      out.write("        } else {\r\n");
      out.write("            // input is valid -- reset the error message\r\n");
      out.write("            input.setCustomValidity('');\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("            \r\n");
      out.write("        <tr>\r\n");
      out.write("                <td colspan=\"2\" align=\"center\">\r\n");
      out.write("                    <input type=\"submit\" value=\"Save\" />\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div> \r\n");
      out.write("    <br>\r\n");
      out.write("  ");

int timeout = session.getMaxInactiveInterval();
response.setHeader("Refresh", timeout + "; URL = loginRedirect.jsp");

      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
